spring.application.name=CadastroDeJedi

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=${DATA_BASE_URL}
spring.datasource.driver=org.h2.Driver
spring.datasource.username=${DATA_BASE_USERNAME}
spring.datasource.password=${DATA_BASE_PASSWORD}

# Configurações do JPA // HIBERNATES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true